version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-tutorialseguranca
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tutorialseguranca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

